version: 0.1

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      - tar -xvf android-sdk_r24.4.1-linux.tgz
      - sudo mv android-sdk-linux /opt/
      - export ANDROID_HOME=/opt/android-sdk-linux
      - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      :$ANDROID_HOME/tools/bin/sdkmanager --licenses
      - /opt/android-sdk-linux/tools/android update sdk --no-ui
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /app/android-debug.apk
  discard-paths: yes
